# Generated by Django 3.2.4 on 2021-07-21 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulo', '0011_alter_articulo_subfamilia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('adress2', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=7)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stripe_token', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticuloOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad', models.IntegerField(default=1)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='articulo.articulo')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='orden.orden')),
            ],
        ),
    ]
