# Generated by Django 3.2.4 on 2021-06-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0002_articulo_upc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='upc',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
