# Generated by Django 3.2.4 on 2021-06-29 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0003_alter_articulo_upc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='upc',
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.ImageField(default=1, upload_to='')),
                ('upc', models.CharField(max_length=18, unique=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.articulo')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.talla')),
            ],
        ),
    ]
