# Generated by Django 3.2.4 on 2021-06-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0004_auto_20210629_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='talla',
        ),
        migrations.AddField(
            model_name='articulo',
            name='variantes',
            field=models.BooleanField(default=False),
        ),
    ]
