# Generated by Django 3.2.4 on 2021-07-08 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0010_alter_variante_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='subfamilia',
            field=models.ForeignKey(default='SIN DEFINIR', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='subfamilia', to='articulo.subfamilia'),
        ),
    ]
