# Generated by Django 3.2.4 on 2021-07-24 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0011_alter_articulo_subfamilia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='marca',
            field=models.ForeignKey(default='SIN DEFINIR', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='marca', to='articulo.marca'),
        ),
    ]
