# Generated by Django 3.2.4 on 2021-07-26 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0013_tallaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talla',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tallaje',
            name='talla',
        ),
        migrations.AddField(
            model_name='articulo',
            name='tallaje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tallajes', to='articulo.tallaje'),
        ),
        migrations.AddField(
            model_name='talla',
            name='tallaje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tallaje', to='articulo.tallaje'),
        ),
    ]
