# Generated by Django 3.2.4 on 2021-08-01 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0015_remove_articulo_variantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarianteArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=5)),
                ('inventario', models.IntegerField(max_length=5)),
                ('upc', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='VarianteTallaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='variante',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='variante',
            name='talla',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='tallaje',
        ),
        migrations.DeleteModel(
            name='Talla',
        ),
        migrations.DeleteModel(
            name='Tallaje',
        ),
        migrations.DeleteModel(
            name='Variante',
        ),
        migrations.AddField(
            model_name='variantetallaje',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.articulo'),
        ),
        migrations.AddField(
            model_name='variantearticulo',
            name='tallaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.variantetallaje'),
        ),
        migrations.AlterUniqueTogether(
            name='variantetallaje',
            unique_together={('modelo', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='variantearticulo',
            unique_together={('tallaje', 'talla')},
        ),
    ]
