# Generated by Django 3.2.4 on 2021-08-01 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0016_auto_20210731_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantearticulo',
            name='inventario',
        ),
    ]
