# Generated by Django 3.2.4 on 2021-08-01 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0020_rename_preciodescuneto_articulo_preciodescuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='tallaje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articulo.variantetallaje'),
        ),
        migrations.AlterUniqueTogether(
            name='variantetallaje',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='variantetallaje',
            name='modelo',
        ),
    ]
