# Generated by Django 3.2.4 on 2021-08-01 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0021_auto_20210731_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantearticulo',
            name='padre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articulo.articulo'),
        ),
    ]
