# Generated by Django 3.2.4 on 2021-08-01 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0022_variantearticulo_padre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='tallaje',
        ),
        migrations.AlterUniqueTogether(
            name='variantearticulo',
            unique_together={('padre', 'talla')},
        ),
        migrations.RemoveField(
            model_name='variantearticulo',
            name='tallaje',
        ),
        migrations.DeleteModel(
            name='VarianteTallaje',
        ),
    ]
